services:
  - type: web
    name: tribe-odyssey
    buildCommand: yarn install && yarn build
    staticPublishPath: ./dist
    maintenance:
      path: /maintenance
      enabled: true
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options 
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
      - type: redirect
        source: /index.html
        destination: /
        statusCode: 404
      - type: redirect
        source: /(.*)/$
        destination: /$1
        statusCode: 404
      - type: redirect
        source: http://*
        destination: https://$HOST
        statusCode: 301
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: tribe-odyssey-data
      mountPath: /data
      sizeGB: 20
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
databases:
  - name: tribe-odyssey-db
    plan: starter
    ipAllowList: []
    backups:
      enabled: true
      retentionPeriodDays: 7