services:
  - type: web
    name: tribe-odyssey
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn preview
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5172
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options 
        value: nosniff
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
      - type: redirect
        source: /index.html
        destination: /
      - type: redirect
        source: /(.*)/$
        destination: /$1
      - type: redirect
        source: http://*
        destination: https://$HOST
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: tribe-odyssey-data
      mountPath: /data
      sizeGB: 20
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
    errorPages:
      404: /404.html
      500: /500.html