services:
  - type: web
    name: tribe-odyssey
    buildCommand: yarn install && yarn build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
      - type: redirect
        source: /index.html
        destination: /
        statusCode: 301 
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: tribe-odyssey-data
      mountPath: /data
      sizeGB: 10
databases:
  - name: tribe-odyssey-db
    plan: starter
    ipAllowList: [] 