import { useEffect } from "react";
import { Box, Container, Typography, styled } from "@mui/material";

// Styled Components
const StyledContainer = styled(Container)({
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
  padding: '64px 16px',
  minHeight: '100vh',
  background: 'linear-gradient(180deg, #14121b 0%, #000000 100%)',
});

const ContentWrapper = styled(Box)({
  maxWidth: '960px',
  width: '100%',
  margin: '0 auto',
  padding: '20px',
});

const GradientTitle = styled(Typography)({
  background: "linear-gradient(180deg, rgb(235, 235, 235) 0%, rgba(235, 235, 235, 0) 100%)",
  WebkitBackgroundClip: "text",
  backgroundClip: "text",
  WebkitTextFillColor: "transparent",
  textFillColor: "transparent",
  fontFamily: "'Montserrat', Helvetica",
  fontWeight: 500,
  fontSize: "80px",
  textAlign: "center",
  letterSpacing: "-2.4px",
  lineHeight: "80px",
  marginTop: '-8px',
  marginBottom: '16px',
  '@media (max-width: 600px)': {
    fontSize: '48px',
    lineHeight: '48px',
  }
});

const Description = styled(Typography)({
  fontFamily: "'Montserrat', Helvetica",
  fontWeight: 400,
  color: "rgba(235, 235, 235, 0.65)",
  fontSize: "18px",
  textAlign: "center",
  lineHeight: "28.8px",
  maxWidth: '746px',
  margin: '0 auto',
  '@media (max-width: 600px)': {
    fontSize: '16px',
    lineHeight: '24px',
    padding: '0 16px',
  }
});

export default function RafflesPage(): JSX.Element {
  useEffect(() => {
    document.title = "Raffles";
  }, []);

  return (
    <StyledContainer maxWidth={false}>
      <ContentWrapper>
        <Box
          display="flex"
          flexDirection="column"
          alignItems="center"
          gap={2}
          position="relative"
        >
          <GradientTitle variant="h1">
            Upcoming Raffles
          </GradientTitle>

          <Box
            display="flex"
            width={{ xs: '100%', md: '746px' }}
            justifyContent="center"
            position="relative"
          >
            <Description variant="body1">
              Use the NANA points generated by staking your TRIBE apes to enter our
              raffles. There are some awesome prizes to be won!
            </Description>
          </Box>

          {/* Add raffle cards or other content here */}
        </Box>
      </ContentWrapper>
    </StyledContainer>
  );
}
